# Generated by Django 4.1.5 on 2023-02-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k99', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='real_pw',
            field=models.TextField(null=True),
        ),
    ]
