# Generated by Django 4.0.3 on 2023-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k99', '0002_customer_real_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_error',
            field=models.IntegerField(null=True),
        ),
    ]
